"""Add remaining models

Revision ID: 2880c9f24d37
Revises: 5606f53a80d7
Create Date: 2026-04-10 09:20:11.756929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2880c9f24d37'
down_revision: Union[str, Sequence[str], None] = '5606f53a80d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('lastMessageText', sa.String(), nullable=True),
    sa.Column('lastMessageAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unreadCount', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('forum_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_channels_id'), 'forum_channels', ['id'], unique=False)
    op.create_index(op.f('ix_forum_channels_slug'), 'forum_channels', ['slug'], unique=True)
    op.create_table('connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('requesterId', sa.String(), nullable=False),
    sa.Column('addresseeId', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED', name='connectionstatusenum'), nullable=True),
    sa.Column('type', sa.Enum('FRIEND', 'MENTORSHIP', name='connectiontypeenum'), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['addresseeId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requesterId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_addresseeId'), 'connections', ['addresseeId'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_requesterId'), 'connections', ['requesterId'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('authorId', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('authorDetails', sa.JSON(), nullable=True),
    sa.Column('publicationYear', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('edition', sa.String(), nullable=True),
    sa.Column('referenceKey', sa.String(), nullable=True),
    sa.Column('associatedCourse', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('pagesCount', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('tableOfContents', sa.JSON(), nullable=True),
    sa.Column('fileUrl', sa.String(), nullable=True),
    sa.Column('previewUrl', sa.String(), nullable=True),
    sa.Column('isPremium', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('downloadsCount', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='documentstatusenum'), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_authorId'), 'documents', ['authorId'], unique=False)
    op.create_index(op.f('ix_documents_createdAt'), 'documents', ['createdAt'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('feed_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('authorId', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'PDF', 'RECOMMENDED_OPPORTUNITY', name='feedposttypeenum'), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('likesCount', sa.Integer(), nullable=True),
    sa.Column('commentsCount', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_posts_authorId'), 'feed_posts', ['authorId'], unique=False)
    op.create_index(op.f('ix_feed_posts_createdAt'), 'feed_posts', ['createdAt'], unique=False)
    op.create_index(op.f('ix_feed_posts_id'), 'feed_posts', ['id'], unique=False)
    op.create_table('forum_topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channelId', sa.String(), nullable=False),
    sa.Column('authorId', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('viewsCount', sa.Integer(), nullable=True),
    sa.Column('repliesCount', sa.Integer(), nullable=True),
    sa.Column('likesCount', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['channelId'], ['forum_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_topics_channelId'), 'forum_topics', ['channelId'], unique=False)
    op.create_index(op.f('ix_forum_topics_createdAt'), 'forum_topics', ['createdAt'], unique=False)
    op.create_index(op.f('ix_forum_topics_id'), 'forum_topics', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversationId', sa.String(), nullable=False),
    sa.Column('senderId', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'DOCUMENT', name='messagetypeenum'), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', name='messagestatusenum'), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversationId'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversationId'), 'messages', ['conversationId'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('authorId', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('SCHOLARSHIP', 'INTERNSHIP', 'JOB', name='opportunitytypeenum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('fundingSource', sa.String(), nullable=True),
    sa.Column('targetAudience', sa.String(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('missions', sa.JSON(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('fundingDetails', sa.JSON(), nullable=True),
    sa.Column('eligibilityRequirements', sa.JSON(), nullable=True),
    sa.Column('selectionCriteria', sa.JSON(), nullable=True),
    sa.Column('applicationProcess', sa.JSON(), nullable=True),
    sa.Column('importantDates', sa.JSON(), nullable=True),
    sa.Column('contactPerson', sa.JSON(), nullable=True),
    sa.Column('requiredDocuments', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contactInfo', sa.String(), nullable=True),
    sa.Column('applyUrl', sa.String(), nullable=True),
    sa.Column('isPremiumOnly', sa.Boolean(), nullable=True),
    sa.Column('isBoosted', sa.Boolean(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_authorId'), 'opportunities', ['authorId'], unique=False)
    op.create_index(op.f('ix_opportunities_createdAt'), 'opportunities', ['createdAt'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_table('forum_replies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topicId', sa.String(), nullable=False),
    sa.Column('authorId', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('likesCount', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topicId'], ['forum_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_replies_id'), 'forum_replies', ['id'], unique=False)
    op.create_index(op.f('ix_forum_replies_topicId'), 'forum_replies', ['topicId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_replies_topicId'), table_name='forum_replies')
    op.drop_index(op.f('ix_forum_replies_id'), table_name='forum_replies')
    op.drop_table('forum_replies')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_createdAt'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_authorId'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversationId'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_forum_topics_id'), table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_createdAt'), table_name='forum_topics')
    op.drop_index(op.f('ix_forum_topics_channelId'), table_name='forum_topics')
    op.drop_table('forum_topics')
    op.drop_index(op.f('ix_feed_posts_id'), table_name='feed_posts')
    op.drop_index(op.f('ix_feed_posts_createdAt'), table_name='feed_posts')
    op.drop_index(op.f('ix_feed_posts_authorId'), table_name='feed_posts')
    op.drop_table('feed_posts')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_createdAt'), table_name='documents')
    op.drop_index(op.f('ix_documents_authorId'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_connections_requesterId'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_addresseeId'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_forum_channels_slug'), table_name='forum_channels')
    op.drop_index(op.f('ix_forum_channels_id'), table_name='forum_channels')
    op.drop_table('forum_channels')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
