"""Ajout de nouvelle table

Revision ID: 521c76b1e0e3
Revises: 9cff078ed7c7
Create Date: 2026-04-22 11:34:25.677499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521c76b1e0e3'
down_revision: Union[str, Sequence[str], None] = '9cff078ed7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_replies', sa.Column('reportsCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_replies', 'reportsCount')
    # ### end Alembic commands ###
