"""Add reportsCount to ForumReply

Revision ID: 74df8b3fc836
Revises: 521c76b1e0e3
Create Date: 2026-04-22 17:36:15.011522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74df8b3fc836'
down_revision: Union[str, Sequence[str], None] = '521c76b1e0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
