"""Add FOLLOWING enum and forum topic status

Revision ID: 8f02c650557a
Revises: 2880c9f24d37
Create Date: 2026-04-10 14:34:00.448569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f02c650557a'
down_revision: Union[str, Sequence[str], None] = '2880c9f24d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    forum_topic_status = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='forumtopicstatusenum')
    forum_topic_status.create(op.get_bind())
    
    op.add_column('forum_topics', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='forumtopicstatusenum'), nullable=True))
    op.execute("ALTER TYPE connectiontypeenum ADD VALUE IF NOT EXISTS 'FOLLOWING'")
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_topics', 'status')
    # ### end Alembic commands ###
