"""Add ForumChannelMember and nested replies

Revision ID: 9675fd80c492
Revises: a0044fa2e808
Create Date: 2026-04-12 11:08:45.582039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9675fd80c492'
down_revision: Union[str, Sequence[str], None] = 'a0044fa2e808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_channel_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channelId', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('joinedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channelId'], ['forum_channels.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_channel_members_channelId'), 'forum_channel_members', ['channelId'], unique=False)
    op.create_index(op.f('ix_forum_channel_members_id'), 'forum_channel_members', ['id'], unique=False)
    op.create_index(op.f('ix_forum_channel_members_userId'), 'forum_channel_members', ['userId'], unique=False)
    op.add_column('forum_replies', sa.Column('parentId', sa.String(), nullable=True))
    op.create_index(op.f('ix_forum_replies_parentId'), 'forum_replies', ['parentId'], unique=False)
    op.create_foreign_key(None, 'forum_replies', 'forum_replies', ['parentId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forum_replies', type_='foreignkey')
    op.drop_index(op.f('ix_forum_replies_parentId'), table_name='forum_replies')
    op.drop_column('forum_replies', 'parentId')
    op.drop_index(op.f('ix_forum_channel_members_userId'), table_name='forum_channel_members')
    op.drop_index(op.f('ix_forum_channel_members_id'), table_name='forum_channel_members')
    op.drop_index(op.f('ix_forum_channel_members_channelId'), table_name='forum_channel_members')
    op.drop_table('forum_channel_members')
    # ### end Alembic commands ###
