"""Add social feed chat and notifications

Revision ID: 9cff078ed7c7
Revises: 9675fd80c492
Create Date: 2026-04-12 11:30:35.510117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cff078ed7c7'
down_revision: Union[str, Sequence[str], None] = '9675fd80c492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('FRIEND_REQUEST', 'OPPORTUNITY_MATCH', 'FORUM_REPLY', 'CHAT_MESSAGE', 'FEED_LIKE', 'FEED_COMMENT', 'MENTION', 'SYSTEM', name='notificationtypeenum'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('isRead', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_createdAt'), 'notifications', ['createdAt'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_userId'), 'notifications', ['userId'], unique=False)
    op.create_table('feed_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('postId', sa.String(), nullable=False),
    sa.Column('authorId', sa.String(), nullable=False),
    sa.Column('parentId', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('likesCount', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parentId'], ['feed_comments.id'], ),
    sa.ForeignKeyConstraint(['postId'], ['feed_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_comments_id'), 'feed_comments', ['id'], unique=False)
    op.create_index(op.f('ix_feed_comments_parentId'), 'feed_comments', ['parentId'], unique=False)
    op.create_index(op.f('ix_feed_comments_postId'), 'feed_comments', ['postId'], unique=False)
    op.create_table('feed_likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('postId', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['postId'], ['feed_posts.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_likes_id'), 'feed_likes', ['id'], unique=False)
    op.create_index(op.f('ix_feed_likes_postId'), 'feed_likes', ['postId'], unique=False)
    op.create_table('feed_comment_likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('commentId', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commentId'], ['feed_comments.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_comment_likes_commentId'), 'feed_comment_likes', ['commentId'], unique=False)
    op.create_index(op.f('ix_feed_comment_likes_id'), 'feed_comment_likes', ['id'], unique=False)
    op.add_column('feed_posts', sa.Column('originalPostId', sa.String(), nullable=True))
    op.create_foreign_key(None, 'feed_posts', 'feed_posts', ['originalPostId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feed_posts', type_='foreignkey')
    op.drop_column('feed_posts', 'originalPostId')
    op.drop_index(op.f('ix_feed_comment_likes_id'), table_name='feed_comment_likes')
    op.drop_index(op.f('ix_feed_comment_likes_commentId'), table_name='feed_comment_likes')
    op.drop_table('feed_comment_likes')
    op.drop_index(op.f('ix_feed_likes_postId'), table_name='feed_likes')
    op.drop_index(op.f('ix_feed_likes_id'), table_name='feed_likes')
    op.drop_table('feed_likes')
    op.drop_index(op.f('ix_feed_comments_postId'), table_name='feed_comments')
    op.drop_index(op.f('ix_feed_comments_parentId'), table_name='feed_comments')
    op.drop_index(op.f('ix_feed_comments_id'), table_name='feed_comments')
    op.drop_table('feed_comments')
    op.drop_index(op.f('ix_notifications_userId'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_createdAt'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
