"""Add CRM and CMS admin fields

Revision ID: a0044fa2e808
Revises: 8f02c650557a
Create Date: 2026-04-11 09:53:41.028700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0044fa2e808'
down_revision: Union[str, Sequence[str], None] = '8f02c650557a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    feed_post_status = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='feedpoststatusenum')
    feed_post_status.create(op.get_bind())
    
    op.add_column('feed_posts', sa.Column('title', sa.String(), nullable=True))
    op.add_column('feed_posts', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='feedpoststatusenum'), nullable=True))
    op.add_column('forum_topics', sa.Column('reportsCount', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reportsCount', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('kycDocumentUrl', sa.String(), nullable=True))
    op.add_column('users', sa.Column('premiumReceiptUrl', sa.String(), nullable=True))
    op.add_column('users', sa.Column('premiumPaymentMethod', sa.String(), nullable=True))
    op.add_column('users', sa.Column('premiumAmount', sa.String(), nullable=True))
    
    op.execute("ALTER TYPE statusenum ADD VALUE IF NOT EXISTS 'SHADOWBANNED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premiumAmount')
    op.drop_column('users', 'premiumPaymentMethod')
    op.drop_column('users', 'premiumReceiptUrl')
    op.drop_column('users', 'kycDocumentUrl')
    op.drop_column('users', 'reportsCount')
    op.drop_column('forum_topics', 'reportsCount')
    op.drop_column('feed_posts', 'status')
    op.drop_column('feed_posts', 'title')
    # ### end Alembic commands ###
